[package]
name = "fakit"
version = "0.2.0"
edition = "2021"
authors = ["sharkLoc <mmtinfo@163.com>"]
rust-version = "1.65.0"
homepage = "https://github.com/sharkLoc/fakit"
description = "fakit: a simple program for fasta file manipulation"
keywords = ["fasta", "fa", "cli", "sequence", "bio"]
readme = "README.md"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.0.0"
clap = { version = "4.0.18", features = ["derive"] }
flate2 = "1.0.24"
rust-htslib = "0.40.2"

